Repository googleapis/java-recommender, pull requests merged in 2020-10, with the labels that each got.

#287 build(java): readme.sh should be executable
  .kokoro/readme.sh
  synth.metadata
Labels: api: recommender, automerge, cla: yes, context: full

#304 chore: refactored tests to get better output from the error stack
  google-cloud-recommender/pom.xml
  google-cloud-recommender/src/test/java/com/google/cloud/recommender/v1beta1/it/ITSystemTest.java
Labels: api: recommender, cla: yes

#300 ci(java): suggest formatting fixes
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: recommender, cla: yes, context: full

#310 chore: regenerate common templates
  .github/snippet-bot.yml
  .github/workflows/approve-readme.yaml
  .kokoro/build.sh
  .kokoro/release/publish_javadoc.sh
  CODE_OF_CONDUCT.md
  renovate.json
  synth.metadata
Labels: api: recommender, automerge, cla: yes, context: full

#317 chore(ci): fix typo in restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#305 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: recommender, cla: yes

#321 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#322 chore(java): enable generated-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#324 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes
