Repository googleapis/java-recommender, pull requests merged in 2020-06, with the labels that each got.

#183 chore: regenerate with updated protoc
  proto-google-cloud-recommender-v1/src/main/java/com/google/cloud/recommender/v1/CostProjection.java
  proto-google-cloud-recommender-v1/src/main/java/com/google/cloud/recommender/v1/GetRecommendationRequest.java
  proto-google-cloud-recommender-v1/src/main/java/com/google/cloud/recommender/v1/Impact.java
  proto-google-cloud-recommender-v1/src/main/java/com/google/cloud/recommender/v1/ListRecommendationsRequest.java
  proto-google-cloud-recommender-v1/src/main/java/com/google/cloud/recommender/v1/ListRecommendationsResponse.java
  proto-google-cloud-recommender-v1/src/main/java/com/google/cloud/recommender/v1/MarkRecommendationClaimedRequest.java
  proto-google-cloud-recommender-v1/src/main/java/com/google/cloud/recommender/v1/MarkRecommendationFailedRequest.java
  proto-google-cloud-recommender-v1/src/main/java/com/google/cloud/recommender/v1/MarkRecommendationSucceededRequest.java
  proto-google-cloud-recommender-v1/src/main/java/com/google/cloud/recommender/v1/Operation.java
  proto-google-cloud-recommender-v1/src/main/java/com/google/cloud/recommender/v1/OperationGroup.java
  proto-google-cloud-recommender-v1/src/main/java/com/google/cloud/recommender/v1/Recommendation.java
  proto-google-cloud-recommender-v1/src/main/java/com/google/cloud/recommender/v1/RecommendationContent.java
  proto-google-cloud-recommender-v1/src/main/java/com/google/cloud/recommender/v1/RecommendationStateInfo.java
  proto-google-cloud-recommender-v1/src/main/java/com/google/cloud/recommender/v1/ValueMatcher.java
  proto-google-cloud-recommender-v1beta1/src/main/java/com/google/cloud/recommender/v1beta1/CostProjection.java
  proto-google-cloud-recommender-v1beta1/src/main/java/com/google/cloud/recommender/v1beta1/GetInsightRequest.java
  proto-google-cloud-recommender-v1beta1/src/main/java/com/google/cloud/recommender/v1beta1/GetRecommendationRequest.java
  proto-google-cloud-recommender-v1beta1/src/main/java/com/google/cloud/recommender/v1beta1/Impact.java
  proto-google-cloud-recommender-v1beta1/src/main/java/com/google/cloud/recommender/v1beta1/Insight.java
  proto-google-cloud-recommender-v1beta1/src/main/java/com/google/cloud/recommender/v1beta1/InsightStateInfo.java
  proto-google-cloud-recommender-v1beta1/src/main/java/com/google/cloud/recommender/v1beta1/ListInsightsRequest.java
  proto-google-cloud-recommender-v1beta1/src/main/java/com/google/cloud/recommender/v1beta1/ListInsightsResponse.java
  proto-google-cloud-recommender-v1beta1/src/main/java/com/google/cloud/recommender/v1beta1/ListRecommendationsRequest.java
  proto-google-cloud-recommender-v1beta1/src/main/java/com/google/cloud/recommender/v1beta1/ListRecommendationsResponse.java
  proto-google-cloud-recommender-v1beta1/src/main/java/com/google/cloud/recommender/v1beta1/MarkInsightAcceptedRequest.java
  proto-google-cloud-recommender-v1beta1/src/main/java/com/google/cloud/recommender/v1beta1/MarkRecommendationClaimedRequest.java
  proto-google-cloud-recommender-v1beta1/src/main/java/com/google/cloud/recommender/v1beta1/MarkRecommendationFailedRequest.java
  proto-google-cloud-recommender-v1beta1/src/main/java/com/google/cloud/recommender/v1beta1/MarkRecommendationSucceededRequest.java
  proto-google-cloud-recommender-v1beta1/src/main/java/com/google/cloud/recommender/v1beta1/Operation.java
  proto-google-cloud-recommender-v1beta1/src/main/java/com/google/cloud/recommender/v1beta1/OperationGroup.java
  proto-google-cloud-recommender-v1beta1/src/main/java/com/google/cloud/recommender/v1beta1/Recommendation.java
  proto-google-cloud-recommender-v1beta1/src/main/java/com/google/cloud/recommender/v1beta1/RecommendationContent.java
  proto-google-cloud-recommender-v1beta1/src/main/java/com/google/cloud/recommender/v1beta1/RecommendationStateInfo.java
  proto-google-cloud-recommender-v1beta1/src/main/java/com/google/cloud/recommender/v1beta1/ValueMatcher.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#185 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#187 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#189 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#191 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#195 feat: promote to GA
  .repo-metadata.json
  README.md
Labels: cla: yes

#201 fix: update retry settings from grpc_service_config
  google-cloud-recommender/src/main/java/com/google/cloud/recommender/v1/stub/RecommenderStubSettings.java
  google-cloud-recommender/src/main/java/com/google/cloud/recommender/v1beta1/stub/RecommenderStubSettings.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#207 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#212 chore: update README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#213 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-recommender/pom.xml
  grpc-google-cloud-recommender-v1/pom.xml
  grpc-google-cloud-recommender-v1beta1/pom.xml
  pom.xml
  proto-google-cloud-recommender-v1/pom.xml
  proto-google-cloud-recommender-v1beta1/pom.xml
Labels: cla: yes

#224 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
