Repository googleapis/java-recommender, pull requests merged in 2020-08, with the labels that each got.

#241 samples: migrate samples from GoogleCloudPlatform/java-docs-samples /recommender/beta/cloud-client
  samples/snippets/src/main/java/com/example/recommender/ListRecommendations.java
  samples/snippets/src/test/java/com/example/recommender/ListRecommendationsTest.java
Labels: cla: yes

#240 chore(docs): add cloud-RAD
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#242 chore: regenerate README samples
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#243 cleanup: removes unused kokoro config files
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#244 build: update dependencies check to only check for runtime and compile scopes
  .kokoro/dependencies.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#251 samples: add presubmit lint check
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#252 build: temporarily disable reporting to unblock releases
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: recommender, cla: yes, context: full
