Repository googleapis/java-recommender, pull requests merged in 2020-09, with the labels that each got.

#253 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: recommender, cla: yes, context: full

#260 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#273 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#274 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#275 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: recommender, automerge, cla: yes

#282 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#284 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
