Repository googleapis/java-recommender, pull requests merged in 2021-01, with the labels that each got.

#386 revert: feat: Add support for "billingAccounts" as another parent resource name for recommendations and insights APIs.
  google-cloud-recommender/src/main/java/com/google/cloud/recommender/v1/RecommenderClient.java
  google-cloud-recommender/src/test/java/com/google/cloud/recommender/v1/RecommenderClientTest.java
  proto-google-cloud-recommender-v1/src/main/java/com/google/cloud/recommender/v1/InsightName.java
  proto-google-cloud-recommender-v1/src/main/java/com/google/cloud/recommender/v1/InsightProto.java
  proto-google-cloud-recommender-v1/src/main/java/com/google/cloud/recommender/v1/InsightTypeName.java
  proto-google-cloud-recommender-v1/src/main/java/com/google/cloud/recommender/v1/ListInsightsRequest.java
  proto-google-cloud-recommender-v1/src/main/java/com/google/cloud/recommender/v1/ListInsightsRequestOrBuilder.java
  proto-google-cloud-recommender-v1/src/main/java/com/google/cloud/recommender/v1/ListRecommendationsRequest.java
  proto-google-cloud-recommender-v1/src/main/java/com/google/cloud/recommender/v1/ListRecommendationsRequestOrBuilder.java
  proto-google-cloud-recommender-v1/src/main/java/com/google/cloud/recommender/v1/Operation.java
  proto-google-cloud-recommender-v1/src/main/java/com/google/cloud/recommender/v1/OperationOrBuilder.java
  proto-google-cloud-recommender-v1/src/main/java/com/google/cloud/recommender/v1/RecommendationName.java
  proto-google-cloud-recommender-v1/src/main/java/com/google/cloud/recommender/v1/RecommendationOuterClass.java
  proto-google-cloud-recommender-v1/src/main/java/com/google/cloud/recommender/v1/RecommenderName.java
  proto-google-cloud-recommender-v1/src/main/java/com/google/cloud/recommender/v1/RecommenderProto.java
  proto-google-cloud-recommender-v1/src/main/proto/google/cloud/recommender/v1/insight.proto
  proto-google-cloud-recommender-v1/src/main/proto/google/cloud/recommender/v1/recommendation.proto
  proto-google-cloud-recommender-v1/src/main/proto/google/cloud/recommender/v1/recommender_service.proto
  synth.metadata
Labels: api: recommender, automerge, cla: yes, context: full

#388 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: recommender, cla: yes

#389 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: recommender, automerge, cla: yes

#391 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: recommender, automerge, cla: yes

#392 chore: update gapic-generator-java to 0.0.18
  google-cloud-recommender/src/main/java/com/google/cloud/recommender/v1/RecommenderClient.java
  google-cloud-recommender/src/main/java/com/google/cloud/recommender/v1/stub/GrpcRecommenderCallableFactory.java
  google-cloud-recommender/src/main/java/com/google/cloud/recommender/v1/stub/RecommenderStub.java
  google-cloud-recommender/src/main/java/com/google/cloud/recommender/v1/stub/RecommenderStubSettings.java
  google-cloud-recommender/src/main/java/com/google/cloud/recommender/v1beta1/RecommenderClient.java
  google-cloud-recommender/src/main/java/com/google/cloud/recommender/v1beta1/RecommenderSettings.java
  google-cloud-recommender/src/main/java/com/google/cloud/recommender/v1beta1/stub/GrpcRecommenderCallableFactory.java
  google-cloud-recommender/src/main/java/com/google/cloud/recommender/v1beta1/stub/GrpcRecommenderStub.java
  google-cloud-recommender/src/main/java/com/google/cloud/recommender/v1beta1/stub/RecommenderStub.java
  synth.metadata
Labels: api: recommender, automerge, cla: yes, context: full

#395 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: recommender, automerge, cla: yes

#398 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: recommender, automerge, cla: yes, context: full

#400 build: migrate to flakybot
  .kokoro/build.sh
Labels: api: recommender, automerge, cla: yes
