Repository googleapis/java-recommender, pull requests merged in 2021-05, with the labels that each got.

#490 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: recommender, automerge, cla: yes, context: none

#491 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: recommender, automerge, cla: yes

#492 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: recommender, cla: yes, context: full

#496 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: recommender, automerge, cla: yes

#499 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: recommender, automerge, cla: yes

#500 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: recommender, automerge, cla: yes, context: full

#502 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: recommender, automerge, cla: yes

#503 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: recommender, automerge, cla: yes, context: full

#509 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: recommender, automerge, cla: yes

#505 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: recommender, automerge, cla: yes, context: full

#511 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: recommender, cla: yes, context: full

#514 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: recommender, automerge, cla: yes
