Repository googleapis/java-recommender, pull requests merged in 2021-08, with the labels that each got.

#553 chore: remove auto generated samples
  README.md
  samples/generated/src/main/java/com/google/cloud/examples/recommender/v1beta1/SampleListRecommendations.java
  samples/generated/src/main/java/com/google/cloud/examples/recommender/v1beta1/recommender.v1beta1.java.yaml
Labels: api: recommender, automerge, cla: yes, samples

#555 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: recommender, automerge, cla: yes

#556 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: recommender, automerge, cla: yes

#557 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: recommender, automerge, cla: yes

#558 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: recommender, automerge, cla: yes

#559 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: recommender, automerge, cla: yes

#560 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: recommender, automerge, cla: yes

#561 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: recommender, automerge, cla: yes

#562 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: recommender, automerge, cla: yes

#563 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: recommender, automerge, cla: yes

#564 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: recommender, automerge, cla: yes

#565 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: recommender, automerge, cla: yes

#568 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: recommender, automerge, cla: yes

#569 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: recommender, automerge, cla: yes

#570 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: recommender

#573 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: recommender, automerge

#574 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: recommender, automerge

#575 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: recommender, automerge

#576 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: recommender, automerge

#577 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: recommender, automerge

#578 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: recommender, automerge

#579 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: recommender, automerge

#580 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: recommender, automerge

#581 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: recommender, automerge

#582 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: recommender, automerge

#583 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: recommender, automerge

#584 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: recommender, automerge

#585 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: recommender, automerge

#586 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: recommender, automerge

#587 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: recommender, automerge

#588 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: recommender, automerge

#589 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: recommender, automerge

#590 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: recommender, automerge

#591 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: recommender, automerge

#592 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: recommender, automerge

#593 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: recommender, automerge

#594 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: recommender, automerge

#595 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: recommender, automerge

#596 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: recommender, automerge

#597 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: cla: yes, api: recommender, automerge

#550 build: configure branch java7 as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: recommender, owlbot:ignore

#601 deps: update dependency com.google.cloud:google-cloud-shared-dependencies to v2
  README.md
  google-cloud-recommender/pom.xml
  pom.xml
Labels: cla: yes, api: recommender, automerge

#607 chore: remove java7 units check from required in master
  .github/sync-repo-settings.yaml
  README.md
Labels: cla: yes, api: recommender, automerge

#612 ci: removing linkage-monitor from the required checks
  .github/sync-repo-settings.yaml
  README.md
Labels: cla: yes, api: recommender, automerge
